name: Publish Zarf Init Package On Tag

on:
  push:
    branches: [ 'main' ]

env:
  # renovate: depName=zarf-dev/zarf
  ZARF_VERSION: 0.59.0

jobs:
  permissions:
    contents: read
    id-token: write
    packages: write

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [ full, minimal ]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: "Login to GHCR"
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: Build image
        uses: ./.github/actions/build-image
        env:
          REGISTRY1_USERNAME: ${{ secrets.REGISTRY1_USERNAME }}
          REGISTRY1_PASSWORD: ${{ secrets.REGISTRY1_PASSWORD }}
        with:
          flavor: ${{ matrix.flavor }}

      - name: ☁️ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::540894334194:role/github-actions/gh-ci-zarf-init-bigbang-k3s-ha
          aws-region: us-east-1

      - name: "Sign and Publish the ${{ matrix.flavor }} image"
        run: |
          zarf package publish build/zarf-init-${{ matrix.flavor }}-amd64-v${ZARF_VERSION}.tar.zst oci://ghcr.io/radiusmethod/zarf-init-bigbang-k3s-ha --signing-key awskms:///alias/zarf-init-bigbang
